package com.projectbusan.bokjido.exception;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum ErrorCode{
    AUTHENTICATION_FAILED(401, "AUTHENTICATION-FAILED", "AUTHENTICATION FAILED ERROR"),
    USER_NOT_FOUND_ERROR(400, "USER-NOT-FOUND", "USER NOT FOUND ERROR"),
    BENEFITS_NOT_FOUND_ERROR(400, "BENEFITS-NOT-FOUND", "BENEFITS NOT FOUND ERROR"),
    BENEFIT_REVIEW_NOT_FOUND_ERROR(400, "BENEFIT-REVIEW-NOT-FOUND", "BENEFIT REVIEWS NOT FOUND ERROR"),

    FACILITY_NOT_FOUND_ERROR(400, "FACILITY-NOT-FOUND", "FACILITY NOT FOUNT ERROR"),
    FACILITY_NOT_DELETABLE(400, "FACILITY-NOT-DELETABLE", "FACILITY NOT DELETABLE"),
    INVALID_ENUM_VALUE(400, "INVALID-ENUM-VALUE", "ENUM VALUE IS INVALID"),
    QNA_NOT_FOUND_ERROR(400, "QNA-NOT-FOUND", "QNA NOT FOUND ERROR"),
    COMMENT_NOT_FOUND_ERROR(400, "COMMENT-NOT-FOUND", "COMMENT NOT FOUND ERROR"),
    PERMISSION_DENIED_FOR_DELETION(400, "PERMISSION-DENIED-FOR-DELETION", "PERMISSION DENIED FOR DELETION"),

    METHOD_ARGUMENT_TYPE_MISMATCHED(400, "METHOD-ARGUMENT-TYPE-MISMATCHED", "METHOD ARGUMENT TYPE MISMATCHED"),
    PARAMETER_BINDING_ERROR(400, "PARAMETER-BINDING-ERROR", "PARAMETER BINDING ERROR"),
    METHOD_NOT_ALLOWED(405, "METHOD-NOT-ALLOWED", "METHOD NOT ALLOWED"),
    INTERNAL_SERVER_ERROR(500, "INTERNAL-SERVER-ERROR", "INTERNAL SERVER ERROR");

    private final int status;
    private final String errorType;
    private final String message;
}
